# Generated by Django 2.2.6 on 2019-11-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=50)),
                ('download_link', models.URLField()),
                ('image', models.ImageField(upload_to='book_covers')),
            ],
        ),
    ]
