# Generated by Django 2.2.6 on 2019-11-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='book_covers'),
        ),
    ]
