# Generated by Django 2.2.6 on 2019-11-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0002_auto_20191102_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebooks',
            options={'verbose_name': 'Ebooks', 'verbose_name_plural': 'Ebooks'},
        ),
        migrations.AlterField(
            model_name='ebooks',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='book_covers'),
        ),
    ]
